#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    Apr 30, 2019 12:34:15 PM CDT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Counter_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = CounterWin (root)
    Counter_support.init(root, top)
    root.mainloop()

w = None
def create_CounterWin(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = CounterWin (w)
    Counter_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_CounterWin():
    global w
    w.destroy()
    w = None

class CounterWin:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        top.style = ttk.Style()
        if sys.platform == "win32":
            top.style.theme_use('winnative')
        top.style.configure('.',background=_bgcolor)
        top.style.configure('.',foreground=_fgcolor)
        top.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("700x400")
        top.title("New Toplevel")
        top.configure(background="#500")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        top.Message1 = tk.Message(top)
        top.Message1.place(relx=0.0, rely=0.2, relheight=0.093, relwidth=0.189)
        top.Message1.configure(background="#fff")
        top.Message1.configure(foreground="#500")
        top.Message1.configure(highlightbackground="#d9d9d9")
        top.Message1.configure(highlightcolor="black")
        top.Message1.configure(text='''Current Count:''')
        top.Message1.configure(width=132)

        top.Message1_1 = tk.Message(top)
        top.Message1_1.place(relx=0.0, rely=0.375, relheight=0.093
                , relwidth=0.189)
        top.Message1_1.configure(background="#fff")
        top.Message1_1.configure(foreground="#500")
        top.Message1_1.configure(highlightbackground="#d9d9d9")
        top.Message1_1.configure(highlightcolor="black")
        top.Message1_1.configure(text='''Max Count:''')
        top.Message1_1.configure(width=132)

        top.Message1_2 = tk.Message(top)
        top.Message1_2.place(relx=0.0, rely=0.55, relheight=0.093
                , relwidth=0.189)
        top.Message1_2.configure(background="#fff")
        top.Message1_2.configure(foreground="#500")
        top.Message1_2.configure(highlightbackground="#d9d9d9")
        top.Message1_2.configure(highlightcolor="black")
        top.Message1_2.configure(text='''Average Count:''')
        top.Message1_2.configure(width=132)

        top.Message1_1 = tk.Message(top)
        top.Message1_1.place(relx=0.0, rely=0.725, relheight=0.093
                , relwidth=0.189)
        top.Message1_1.configure(background="#fff")
        top.Message1_1.configure(font="-family {Segoe UI} -size 8")
        top.Message1_1.configure(foreground="#500")
        top.Message1_1.configure(highlightbackground="#d9d9d9")
        top.Message1_1.configure(highlightcolor="black")
        top.Message1_1.configure(text='''Room Occupancy:''')
        top.Message1_1.configure(width=132)

        top.Button1 = tk.Button(top)
        top.Button1.place(relx=0.714, rely=0.0, height=50, width=200)
        top.Button1.configure(activebackground="#ececec")
        top.Button1.configure(activeforeground="#000")
        top.Button1.configure(background="#fff")
        top.Button1.configure(disabledforeground="#a3a3a3")
        top.Button1.configure(foreground="#500")
        top.Button1.configure(highlightbackground="#d9d9d9")
        top.Button1.configure(highlightcolor="black")
        top.Button1.configure(pady="0")
        top.Button1.configure(text='''Options''')

        top.Button2 = tk.Button(top)
        top.Button2.place(relx=0.714, rely=0.125, height=50, width=200)
        top.Button2.configure(activebackground="#ececec")
        top.Button2.configure(activeforeground="#500")
        top.Button2.configure(background="#fff")
        top.Button2.configure(disabledforeground="#a3a3a3")
        top.Button2.configure(foreground="#500")
        top.Button2.configure(highlightbackground="#d9d9d9")
        top.Button2.configure(highlightcolor="black")
        top.Button2.configure(pady="0")
        top.Button2.configure(text='''Save and Quit''')
        top.Button2.configure(width=200)

        top.Message2 = tk.Message(top)
        top.Message2.place(relx=0.2, rely=0.2, relheight=0.093, relwidth=0.046)
        top.Message2.configure(background="#fff")
        top.Message2.configure(foreground="#500")
        top.Message2.configure(highlightbackground="#d9d9d9")
        top.Message2.configure(highlightcolor="black")
        top.Message2.configure(text='''0''')
        top.Message2.configure(width=90)

        top.Message2_2 = tk.Message(top)
        top.Message2_2.place(relx=0.2, rely=0.375, relheight=0.093
                , relwidth=0.046)
        top.Message2_2.configure(background="#d9d9d9")
        top.Message2_2.configure(foreground="#000000")
        top.Message2_2.configure(highlightbackground="#d9d9d9")
        top.Message2_2.configure(highlightcolor="black")
        top.Message2_2.configure(text='''0''')
        top.Message2_2.configure(width=90)

        top.Message2_3 = tk.Message(top)
        top.Message2_3.place(relx=0.2, rely=0.55, relheight=0.093
                , relwidth=0.046)
        top.Message2_3.configure(background="#d9d9d9")
        top.Message2_3.configure(foreground="#000000")
        top.Message2_3.configure(highlightbackground="#d9d9d9")
        top.Message2_3.configure(highlightcolor="black")
        top.Message2_3.configure(text='''0''')
        top.Message2_3.configure(width=90)

        top.TProgressbar1 = ttk.Progressbar(top)
        top.TProgressbar1.place(relx=0.2, rely=0.725, relwidth=0.214
                , relheight=0.0, height=37)
        top.TProgressbar1.configure(length="150")

        top.Message2_4 = tk.Message(top)
        top.Message2_4.place(relx=0.429, rely=0.725, relheight=0.093
                , relwidth=0.046)
        top.Message2_4.configure(background="#fff")
        top.Message2_4.configure(foreground="#500")
        top.Message2_4.configure(highlightbackground="#d9d9d9")
        top.Message2_4.configure(highlightcolor="black")
        top.Message2_4.configure(text='''0%''')
        top.Message2_4.configure(width=90)

if __name__ == '__main__':
    vp_start_gui()





