#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    Apr 27, 2019 11:56:32 AM CDT  platform: Windows NT

import sys 
 
try:
    import Tkinter as tk
except ImportError as e:
     import tkinter as tk
    
try:
    import ttk
    py3 = False
except ImportError as e:
    import tkinter.ttk as ttk
    py3 = True
    
import Main_support
 
def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    Main_support.init(root, top)
    root.mainloop()
 
w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    Main_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1024x600+650+150")
        top.title("New Toplevel")
        top.configure(background="#500")

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.059, rely=0.167, height=150, width=900)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#fff")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI} -size 24")
        self.Button1.configure(foreground="#500")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Start New''')
        self.Button1.configure(width=878)

        self.Button1_1 = tk.Button(top)
        self.Button1_1.place(relx=0.059, rely=0.433, height=150, width=900)
        self.Button1_1.configure(activebackground="#ececec")
        self.Button1_1.configure(activeforeground="#000000")
        self.Button1_1.configure(background="#fff")
        self.Button1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1.configure(font="-family {Segoe UI} -size 24")
        self.Button1_1.configure(foreground="#500")
        self.Button1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1.configure(highlightcolor="black")
        self.Button1_1.configure(pady="0")
        self.Button1_1.configure(text='''Options''')

        self.Button1_2 = tk.Button(top)
        self.Button1_2.place(relx=0.059, rely=0.7, height=150, width=900)
        self.Button1_2.configure(activebackground="#ececec")
        self.Button1_2.configure(activeforeground="#000000")
        self.Button1_2.configure(background="#fff")
        self.Button1_2.configure(disabledforeground="#a3a3a3")
        self.Button1_2.configure(font="-family {Segoe UI} -size 24")
        self.Button1_2.configure(foreground="#500")
        self.Button1_2.configure(highlightbackground="#d9d9d9")
        self.Button1_2.configure(highlightcolor="black")
        self.Button1_2.configure(pady="0")
        self.Button1_2.configure(text='''Quit''')

        self.Message1 = tk.Message(top)
        self.Message1.place(relx=0.059, rely=0.0, relheight=0.167
                , relwidth=0.879)
        self.Message1.configure(background="#500")
        self.Message1.configure(font="-family {Segoe UI} -size 24")
        self.Message1.configure(foreground="#fff")
        self.Message1.configure(highlightbackground="#500")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''Main Menu:''')
        self.Message1.configure(width=252)

if __name__ == '__main__':
    vp_start_gui()
