   1 #! /usr/bin/env python
   2 #  -*- coding: utf-8 -*-
   3 #
   4 # GUI module generated by PAGE version 4.22
   5 #  in conjunction with Tcl version 8.6
   6 #    Apr 27, 2019 11:56:32 AM CDT  platform: Windows NT
   7 
   8 import sys
   9 
  10 try:
  11     import Tkinter as tk
  12 except ImportError:
  13     import tkinter as tk
  14 
  15 try:
  16     import ttk
  17     py3 = False
  18 except ImportError:
  19     import tkinter.ttk as ttk
  20     py3 = True
  21 
  22 import Main_support
  23 
  24 def vp_start_gui():
  25     '''Starting point when module is the main routine.'''
  26     global val, w, root
  27     root = tk.Tk()
  28     top = Toplevel1 (root)
  29     Main_support.init(root, top)
  30     root.mainloop()
  31 
  32 w = None
  33 def create_Toplevel1(root, *args, **kwargs):
  34     '''Starting point when module is imported by another program.'''
  35     global w, w_win, rt
  36     rt = root
  37     w = tk.Toplevel (root)
  38     top = Toplevel1 (w)
  39     Main_support.init(w, top, *args, **kwargs)
  40     return (w, top)
  41 
  42 def destroy_Toplevel1():
  43     global w
  44     w.destroy()
  45     w = None
  46 
  47 class Toplevel1:
  48     def __init__(self, top=None):
  49         '''This class configures and populates the toplevel window.
  50            top is the toplevel containing window.'''
  51         _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
  52         _fgcolor = '#000000'  # X11 color: 'black'
  53         _compcolor = '#d9d9d9' # X11 color: 'gray85'
  54         _ana1color = '#d9d9d9' # X11 color: 'gray85'
  55         _ana2color = '#ececec' # Closest X11 color: 'gray92'
  56 
  57         top.geometry("1024x600+650+150")
  58         top.title("New Toplevel")
  59         top.configure(background="#500")
  60 
  61         self.Button1 = tk.Button(top)
  62         self.Button1.place(relx=0.059, rely=0.167, height=150, width=900)
  63         self.Button1.configure(activebackground="#ececec")
  64         self.Button1.configure(activeforeground="#000000")
  65         self.Button1.configure(background="#fff")
  66         self.Button1.configure(disabledforeground="#a3a3a3")
  67         self.Button1.configure(font="-family {Segoe UI} -size 24")
  68         self.Button1.configure(foreground="#500")
  69         self.Button1.configure(highlightbackground="#d9d9d9")
  70         self.Button1.configure(highlightcolor="black")
  71         self.Button1.configure(pady="0")
  72         self.Button1.configure(text='''Start New''')
  73         self.Button1.configure(width=878)
  74 
  75         self.Button1_1 = tk.Button(top)
  76         self.Button1_1.place(relx=0.059, rely=0.433, height=150, width=900)
  77         self.Button1_1.configure(activebackground="#ececec")
  78         self.Button1_1.configure(activeforeground="#000000")
  79         self.Button1_1.configure(background="#fff")
  80         self.Button1_1.configure(disabledforeground="#a3a3a3")
  81         self.Button1_1.configure(font="-family {Segoe UI} -size 24")
  82         self.Button1_1.configure(foreground="#500")
  83         self.Button1_1.configure(highlightbackground="#d9d9d9")
  84         self.Button1_1.configure(highlightcolor="black")
  85         self.Button1_1.configure(pady="0")
  86         self.Button1_1.configure(text='''Options''')
  87 
  88         self.Button1_2 = tk.Button(top)
  89         self.Button1_2.place(relx=0.059, rely=0.7, height=150, width=900)
  90         self.Button1_2.configure(activebackground="#ececec")
  91         self.Button1_2.configure(activeforeground="#000000")
  92         self.Button1_2.configure(background="#fff")
  93         self.Button1_2.configure(disabledforeground="#a3a3a3")
  94         self.Button1_2.configure(font="-family {Segoe UI} -size 24")
  95         self.Button1_2.configure(foreground="#500")
  96         self.Button1_2.configure(highlightbackground="#d9d9d9")
  97         self.Button1_2.configure(highlightcolor="black")
  98         self.Button1_2.configure(pady="0")
  99         self.Button1_2.configure(text='''Quit''')
 100 
 101         self.Message1 = tk.Message(top)
 102         self.Message1.place(relx=0.059, rely=0.0, relheight=0.167
 103                 , relwidth=0.879)
 104         self.Message1.configure(background="#500")
 105         self.Message1.configure(font="-family {Segoe UI} -size 24")
 106         self.Message1.configure(foreground="#fff")
 107         self.Message1.configure(highlightbackground="#500")
 108         self.Message1.configure(highlightcolor="black")
 109         self.Message1.configure(text='''Main Menu:''')
 110         self.Message1.configure(width=252)
 111 
 112 if __name__ == '__main__':
 113     vp_start_gui()
 114 
 115 

