#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    Apr 29, 2019 12:22:20 PM CDT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import OptionMenu_support
import Main, Main_support

def vp_start_gui_opt():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    OptionMenu_support.set_Tk_var()
    top = OptionMenu (root)
    OptionMenu_support.init(root, top)
    root.mainloop()

w = None
def create_OptionMenu(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    OptionMenu_support.set_Tk_var()
    top = OptionMenu (w)
    OptionMenu_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_OptionMenu():
    global w
    w.destroy()
    w = None

class OptionMenu:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        top.geometry("700x400")
        top.title("New Toplevel")
        top.configure(background="#500")
        top.configure(pady="1")

        top.Spinbox1 = tk.Spinbox(top, from_=1.0, to=100.0)
        top.Spinbox1.place(relx=0.386, rely=0.275, relheight=0.1
                , relwidth=0.214)
        top.Spinbox1.configure(activebackground="#f9f9f9")
        top.Spinbox1.configure(background="white")
        top.Spinbox1.configure(buttonbackground="#d9d9d9")
        top.Spinbox1.configure(disabledforeground="#a3a3a3")
        top.Spinbox1.configure(foreground="#500")
        top.Spinbox1.configure(highlightbackground="black")
        top.Spinbox1.configure(highlightcolor="black")
        top.Spinbox1.configure(insertbackground="black")
        top.Spinbox1.configure(selectbackground="#c4c4c4")
        top.Spinbox1.configure(selectforeground="black")
        top.Spinbox1.configure(textvariable=OptionMenu_support.spinbox)
        top.Spinbox1.configure(width=148)

        top.Message1 = tk.Message(top)
        top.Message1.place(relx=0.0, rely=0.0, relheight=0.25, relwidth=1.0)
        top.Message1.configure(background="#500")
        top.Message1.configure(font="-family {Segoe UI} -size 16")
        top.Message1.configure(foreground="#fff")
        top.Message1.configure(highlightbackground="#d9d9d9")
        top.Message1.configure(highlightcolor="black")
        top.Message1.configure(text='''Room Capacity:''')
        top.Message1.configure(width=700)

        top.Message1_1 = tk.Message(top)
        top.Message1_1.place(relx=0.0, rely=0.375, relheight=0.25, relwidth=1.0)

        top.Message1_1.configure(background="#500")
        top.Message1_1.configure(font="-family {Segoe UI} -size 16")
        top.Message1_1.configure(foreground="#fff")
        top.Message1_1.configure(highlightbackground="#d9d9d9")
        top.Message1_1.configure(highlightcolor="black")
        top.Message1_1.configure(text='''Event Name:''')
        top.Message1_1.configure(width=700)

        top.Entry1 = tk.Entry(top)
        top.Entry1.place(relx=0.0, rely=0.563,height=50, relwidth=1.0)
        top.Entry1.configure(background="white")
        top.Entry1.configure(disabledforeground="#a3a3a3")
        top.Entry1.configure(font="TkFixedFont")
        top.Entry1.configure(foreground="#500")
        top.Entry1.configure(insertbackground="black")
        top.Entry1.configure(textvariable=OptionMenu_support.event)

        top.Button1 = tk.Button(top)
        top.Button1.place(relx=0.343, rely=0.713, height=100, width=200)
        top.Button1.configure(activebackground="#ececec")
        top.Button1.configure(activeforeground="#000000")
        top.Button1.configure(background="#fff")
        top.Button1.configure(disabledforeground="#a3a3a3")
        top.Button1.configure(font="-family {Segoe UI} -size 12")
        top.Button1.configure(foreground="#500")
        top.Button1.configure(highlightbackground="#d9d9d9")
        top.Button1.configure(highlightcolor="black")
        top.Button1.configure(pady="0")
        top.Button1.configure(text='''Done''')
        top.Button1.configure(command = top.destroy)




